theme: jekyll-theme-cayman
title: Bienvenidos a mi nueva web de contenidos
description: Aquí publicaré mis ideas sobre código Python aplicado a la construcción. Espero que os ayude.
p: Esto es una prueba 
